name: dca-sitter-indexer
preload_handlers: true
contracts:
  - name: ERC20
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
        field_selection:
          transaction_fields:
            - hash
            - to
          block_fields:
            - timestamp
            - number
networks:
  - id: 10143
    start_block: 0
    contracts:
      - name: ERC20
        address:
          - ${WMON_ADDRESS:-0x760AfE86e5de5fa0Ee542fc7B7B713e1c5425701}
